### ISSUE TITLE
iOS - builds failing because of missing file dependency again

### ISSUE THREAD

**Issue by gabaum10** [BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK#71]
Guys, somehow in NPM version 2.0.3 another missing file seems to have been introduced.

Failed to install 'io.branch.sdk':CordovaError: Uh oh!
"/private/project/cordova/plugins/io.branch.sdk/src/ios/dependencies/Branch-SDK/BNCContentDiscoveryManager.m" not found!
    at copyFile (/private/project/cordova/lib/plugman/pluginHandlers.js:261:36)
    at copyNewFile (/private/project/cordova/lib/plugman/pluginHandlers.js:293:5)
    at installHelper (/private/project/cordova/lib/plugman/pluginHandlers.js:212:9)
    at handlers.source-file.install (/private/project/cordova/lib/plugman/pluginHandlers.js:34:13)
    at Object.ActionStack.process (/private/project/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at Plugman.addPlugin (/private/project/cordova/lib/plugman/Plugman.js:82:20)
    at Api.addPlugin (/private/project/cordova/Api.js:187:53)
    at handleInstall (/usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:602:6)
    at /usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/plugman/install.js:391:24
    at _fulfilled (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:787:54)
Uh oh!
"/private/project/cordova/plugins/io.branch.sdk/src/ios/dependencies/Branch-SDK/BNCContentDiscoveryManager.m" not found!

**Comment by gabaum10** [comment]
Works fine in 2.0.2 so I'll just roll back to that for now.

**Comment by harshabonthu** [comment]
@aaustin @renesansz `Branch-SDK` folder is missing in `/src/ios/dependencies/`. I deleted that folder when I replaced with .framework file, it should be added back to support npm.

**Comment by aaustin** [comment]
Hey team - I just added the source code that was missing and redeployed to NPM. This should be resolved.

**Comment by gabaum10** [comment]
It's still failing on iOS with a different error now.  Do you want me to open a new issue?

CompileC build/VeociDEV.build/Release-iphoneos/VeociDEV.build/Objects-normal/armv7/AppDelegate+BranchSdk.o VeociDEV/Plugins/io.branch.sdk/AppDelegate+BranchSdk.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /project
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -gmodules -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/var/folders/lt/xxbrk07x45bdj1fl3wjgf8yc0000gn/C/org.llvm.clang/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=8.0 -g -fvisibility=hidden -Wno-sign-conversion -iquote /project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/VeociDEV-generated-files.hmap -I/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/VeociDEV-own-target-headers.hmap -I/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/VeociDEV-all-target-headers.hmap -iquote /project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/VeociDEV-project-headers.hmap -I/project/build/include -I/project/build/usr/local/lib/include -I/project/build/UninstalledProducts/include -I/project/build/UninstalledProducts/iphoneos/include -I/project/build -I/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/DerivedSources/armv7 -I/project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/DerivedSources -F/project/build -include /var/folders/lt/xxbrk07x45bdj1fl3wjgf8yc0000gn/C/com.apple.DeveloperTools/7.1-7B91b/Xcode/SharedPrecompiledHeaders/VeociDEV-Prefix-dukfhgdnfczgxtdviuddsqbnmmyt/VeociDEV-Prefix.pch -MMD -MT dependencies -MF /project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/Objects-normal/armv7/AppDelegate+BranchSdk.d --serialize-diagnostics /project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/Objects-normal/armv7/AppDelegate+BranchSdk.dia -c /project/VeociDEV/Plugins/io.branch.sdk/AppDelegate+BranchSdk.m -o /project/build/VeociDEV.build/Release-iphoneos/VeociDEV.build/Objects-normal/armv7/AppDelegate+BranchSdk.o
/project/VeociDEV/Plugins/io.branch.sdk/AppDelegate+BranchSdk.m:10:9: fatal error: 'Branch/Branch.h' file not found
#import <Branch/Branch.h>
        ^
1 error generated.

**Comment by aaustin** [comment]
Ugh - I know why. One sec. Deploying an update to make the correct reference.

**Comment by jacksonkr** [comment]
I tried everything, and I mean *everything* to get this to work. This was my solution after hours and hours of installing / reinstalling everything.

#`npm install -g ios-deploy`

    $ ionic info
    
    Your system information:
    
    Cordova CLI: 6.4.0 
    Ionic CLI Version: 2.1.13
    Ionic App Lib Version: 2.1.7
    ios-deploy version: 1.9.0 
    ios-sim version: 5.0.13 
    OS: OS X El Capitan
    Node Version: v7.1.0
    Xcode version: Xcode 8.2.1 Build version 8C1002
